// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/frameforge-dashboard/Current.tsx": () => import("../components/mockups/frameforge-dashboard/Current.tsx"),
  "./components/mockups/frameforge-dashboard/Polished.tsx": () => import("../components/mockups/frameforge-dashboard/Polished.tsx")
};
